export enum routingsTypes {
  ROUTINGS_SELECT_DATA = 'ROUTINGS_SELECT_DATA',
  FETCH_ROUTINGS_REQUEST = 'FETCH_ROUTINGS_REQUEST',
  FETCH_ROUTINGS_SUCCESS = 'FETCH_ROUTINGS_SUCCESS',
  FETCH_ROUTINGS_FAILURE = 'FETCH_ROUTINGS_FAILURE',
}
